const words=[
    ['不足　l','luck'],
    ['分離する s','separate'],
    ['分割する d','divide',],
    ['緊急の u','urgent'],
    ['貢献する c','contribute'],
    ['出産 b','birth'],
    ['人口 p','population'],
    ['層 g','generation'],
    ['青春時代 y','youth'],
    ['隣人 n','neighbor'],
    ['近所 n','neighborhood'],
    ['出生率 b','birthrate'],
    ['障害 d','disorder'],
    ['看病する n','nurse'],
    ['老人ホーム n　h','nursing home'],
    ['保育園 n','nursery'],
    ['教育する e','educate'],
    ['獲得する a','acquire'],
    ['獲得 a','acquisition'],
    ['学習過程 l　p','learning process'],
    ['解く s','solve'],
    ['問題解決能力 p　s','problem-solving skills'],
    ['解決策 s','solution'],
    ['活発な a','active'],
    ['攻撃的な a','aggressive'],
    ['能力 c','capacity'],
    ['性格 p','personality'],
    ['からかう t','tease'],
    [' いじめっこ b','bully'],
    ['好奇心の強い c','curious'],
];