const words=[
['商品 g','goods'],
['コンサルタント c','consultant'],
['義務 d','duty'],
['引退するr','retire'],
['地位 s','status'],
['危険 r','risk'],
['時間を守る p','punctual'],
['拡大する e','expand'],
['拡張 e','extension'],
['延長する e','extend'],
['余分の e','extra'],
['要素 e','element'],
['本部 h','headquarters'],
['枝/支店 b','branch'],
['パートタイムの p','part-time'],
['フルタイムの f','full-time'],
['同僚 c','coworker'],
['秘書 s','secretary'],
['仕事 t','task'],
['技術 s','skill'],
['優先 p','priority'],
['会議 c','conference'],
['評価する e','evaluate'],
['意見 f','feedback'],
['予定する s','schedule'],
['世界/世間 w','world'],
['文学 l','literature'],
['図書館/書斎 l','library'],
['百科事典 e','encyclopedia'],
['伝記b','biography'],
];