const words=[
    ['車 v','vehicle'],
    ['地下鉄 s','subway'],
    ['免許 l','licence'],
    ['遅らせる d','delay'],
    ['発表する a','announce'],
    ['源 s','source'],
    ['真実 t','truth'],
    ['偽の f','fake'],
    ['科学的な s','scientific'],
    ['実験 e','experiment'],
    ['材料、原料 m','material'],
    ['物質 s','substance'],
    ['液体 l','liquid'],
    ['燃やす b','burn'],
    ['茹でる/沸騰する b','boil'],
    ['凍る/凍らせる f','freeze'],
    ['環境 e','environment'],
    ['保護する p','protect'],
    ['保護 p','protection'],
    ['汚染 p','pollution'],
    ['植物/工場/植える p','plant'],
    ['つまむ、摘み取る p','pick'],
    ['地球規模の g','global'],
    ['地球 g','globe'],
    ['酸素 o','oxygen'],
    ['二酸化炭素 c d','carbon dioxide'],
    ['吸収する a','absorb'],
    ['極 p','pole'],
    ['集める c','collect'],
    ['ごみ g','garbage'],


	];